# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 7.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.  Use Unicode::UCD to access the Unicode character data
# base.


return <<'END';
V52
3057
3058
3441
3442
4987
4988
8557
8558
8573
8574
20336
20337
30334
30335
38476
38477
65817
65818
65867
65868
65874
65875
65898
65899
66291
66292
66517
66518
67677
67678
67759
67760
67865
67866
68166
68167
68335
68336
68446
68447
68478
68479
68527
68528
69234
69235
69732
69733
70131
70132
93020
93021
END
