# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 7.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.  Use Unicode::UCD to access the Unicode character data
# base.


return <<'END';
V54
4979
4980
9331
9332
9351
9352
9371
9372
9460
9461
12345
12346
12873
12874
21316
21317
24319
24320
65809
65810
66283
66284
66516
66517
67676
67677
67711
67712
67758
67759
67864
67865
68165
68166
68255
68256
68334
68335
68445
68446
68477
68478
68526
68527
69226
69227
69724
69725
70123
70124
71915
71916
119658
119659
END
