# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 7.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.  Use Unicode::UCD to access the Unicode character data
# base.


return <<'END';
V82
768
773
774
781
783
784
785
786
787
789
795
796
803
809
813
815
816
818
824
825
834
835
837
838
1619
1622
2364
2365
2494
2495
2519
2520
2878
2879
2902
2904
3006
3007
3031
3032
3158
3159
3266
3267
3285
3287
3390
3391
3415
3416
3530
3531
3535
3536
3551
3552
4142
4143
4449
4470
4520
4547
6965
6966
12441
12443
69818
69819
69927
69928
70462
70463
70487
70488
70832
70833
70842
70843
70845
70846
71087
71088
END
