# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 7.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.  Use Unicode::UCD to access the Unicode character data
# base.


return <<'END';
V88
34
35
39
42
91
92
93
94
123
124
125
126
171
172
187
188
3898
3902
5787
5789
8216
8224
8249
8251
8261
8263
8317
8319
8333
8335
8968
8972
9001
9003
10075
10081
10088
10102
10181
10183
10214
10224
10627
10649
10712
10716
10748
10750
11776
11790
11804
11806
11808
11818
11842
11843
12296
12306
12308
12316
12317
12320
64830
64832
65047
65049
65077
65093
65095
65097
65113
65119
65288
65290
65339
65340
65341
65342
65371
65372
65373
65374
65375
65377
65378
65380
128630
128633
END
