# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 7.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.  Use Unicode::UCD to access the Unicode character data
# base.


return <<'END';
V52
183
184
720
722
1600
1601
2042
2043
3654
3655
3782
3783
6154
6155
6211
6212
6823
6824
7222
7223
7291
7292
12293
12294
12337
12342
12445
12447
12540
12543
40981
40982
42508
42509
43471
43472
43494
43495
43632
43633
43741
43742
43763
43765
65392
65393
70493
70494
71110
71113
92994
92996
END
