# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 7.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.  Use Unicode::UCD to access the Unicode character data
# base.


return <<'END';
V90
3056
3057
3440
3441
4978
4979
8553
8554
8569
8570
9321
9322
9341
9342
9361
9362
9470
9471
10111
10112
10121
10122
10131
10132
12344
12345
12841
12842
12872
12873
12937
12938
20160
20161
21313
21314
25342
25343
63859
63860
63997
63998
65808
65809
65865
65866
65872
65873
65879
65880
65888
65893
66282
66283
66338
66339
66515
66516
67675
67676
67710
67711
67757
67758
67863
67864
68164
68165
68254
68255
68333
68334
68444
68445
68476
68477
68525
68526
69225
69226
69723
69724
70122
70123
71914
71915
93019
93020
119657
119658
END
