# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 7.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.  Use Unicode::UCD to access the Unicode character data
# base.


return <<'END';
V104
1568
1569
1574
1575
1576
1577
1578
1583
1587
1600
1601
1608
1609
1611
1646
1648
1656
1672
1690
1728
1729
1731
1740
1741
1742
1743
1744
1746
1786
1789
1791
1792
1810
1813
1818
1822
1823
1832
1833
1834
1835
1836
1837
1839
1870
1881
1884
1899
1901
1905
1906
1907
1909
1912
1914
1920
1994
2027
2113
2118
2120
2121
2122
2132
2133
2134
2208
2218
2223
2225
6151
6152
6176
6264
6279
6313
6314
6315
43072
43122
68288
68293
68307
68311
68312
68317
68318
68321
68331
68335
68480
68481
68482
68483
68486
68489
68490
68492
68493
68494
68496
68497
68525
68527
END
