# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 7.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.  Use Unicode::UCD to access the Unicode character data
# base.


return <<'END';
V100
1570
1574
1575
1576
1577
1578
1583
1587
1608
1609
1649
1652
1653
1656
1672
1690
1728
1729
1731
1740
1741
1742
1743
1744
1746
1748
1749
1750
1774
1776
1808
1809
1813
1818
1822
1823
1832
1833
1834
1835
1836
1837
1839
1840
1869
1870
1881
1884
1899
1901
1905
1906
1907
1909
1912
1914
2112
2113
2118
2120
2121
2122
2132
2133
2218
2221
2222
2223
2225
2227
68293
68294
68295
68296
68297
68299
68302
68307
68317
68318
68321
68322
68324
68325
68335
68336
68481
68482
68483
68486
68489
68490
68492
68493
68494
68496
68497
68498
68521
68525
END
