# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 7.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.  Use Unicode::UCD to access the Unicode character data
# base.


return <<'END';
V62
1424
1425
1470
1471
1472
1473
1475
1476
1478
1479
1480
1536
1984
2027
2036
2038
2042
2070
2074
2075
2084
2085
2088
2089
2094
2137
2140
2208
8207
8208
64285
64286
64287
64297
64298
64336
67584
67871
67872
68097
68100
68101
68103
68108
68112
68152
68155
68159
68160
68325
68327
68409
68416
69216
69247
69632
124928
125136
125143
126464
126720
126976
END
