# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 7.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.  Use Unicode::UCD to access the Unicode character data
# base.



# The name this swash is to be known by, with the format of the mappings in
# the main body of the table, and what all code points missing from this file
# map to.
$utf8::SwashInfo{'ToScx'}{'format'} = 'sw'; # string, but some elements are interpreted as a list; white space occurs only as list item separators
$utf8::SwashInfo{'ToScx'}{'missing'} = 'Unknown';

return <<'END';
0	40	Common
41	5A	Latin
5B	60	Common
61	7A	Latin
7B	A9	Common
AA		Latin
AB	B9	Common
BA		Latin
BB	BF	Common
C0	D6	Latin
D7		Common
D8	F6	Latin
F7		Common
F8	2B8	Latin
2B9	2DF	Common
2E0	2E4	Latin
2E5	2E9	Common
2EA	2EB	Bopomofo
2EC	2FF	Common
300	341	Inherited
342		Greek
343	344	Inherited
345		Greek
346	362	Inherited
363	36F	Latin
370	373	Greek
374		Common
375	377	Greek
37A	37D	Greek
37E		Common
37F		Greek
384		Greek
385		Common
386		Greek
387		Common
388	38A	Greek
38C		Greek
38E	3A1	Greek
3A3	3E1	Greek
3E2	3EF	Coptic
3F0	3FF	Greek
400	484	Cyrillic
485	486	Cyrillic Latin
487	52F	Cyrillic
531	556	Armenian
559	55F	Armenian
561	587	Armenian
589		Armenian Georgian
58A		Armenian
58D	58F	Armenian
591	5C7	Hebrew
5D0	5EA	Hebrew
5F0	5F4	Hebrew
600	604	Arabic
605		Common
606	60B	Arabic
60C		Arabic Syriac Thaana
60D	61A	Arabic
61B		Arabic Syriac Thaana
61C		Common
61E		Arabic
61F		Arabic Syriac Thaana
620	63F	Arabic
640		Arabic Mandaic Manichaean Psalter_Pahlavi Syriac
641	64A	Arabic
64B	655	Arabic Syriac
656	65F	Arabic
660	669	Arabic Thaana
66A	66F	Arabic
670		Arabic Syriac
671	6DC	Arabic
6DD		Common
6DE	6FF	Arabic
700	70D	Syriac
70F	74A	Syriac
74D	74F	Syriac
750	77F	Arabic
780	7B1	Thaana
7C0	7FA	Nko
800	82D	Samaritan
830	83E	Samaritan
840	85B	Mandaic
85E		Mandaic
8A0	8B2	Arabic
8E4	8FF	Arabic
900	950	Devanagari
951	952	Devanagari Latin
953	963	Devanagari
964		Bengali Devanagari Grantha Gujarati Gurmukhi Kannada Mahajani Malayalam Oriya Khudawadi Sinhala Syloti_Nagri Takri Tamil Telugu Tirhuta
965		Bengali Devanagari Grantha Gujarati Gurmukhi Kannada Limbu Mahajani Malayalam Oriya Khudawadi Sinhala Syloti_Nagri Takri Tamil Telugu Tirhuta
966	96F	Devanagari Kaithi Mahajani
970	97F	Devanagari
980	983	Bengali
985	98C	Bengali
98F	990	Bengali
993	9A8	Bengali
9AA	9B0	Bengali
9B2		Bengali
9B6	9B9	Bengali
9BC	9C4	Bengali
9C7	9C8	Bengali
9CB	9CE	Bengali
9D7		Bengali
9DC	9DD	Bengali
9DF	9E3	Bengali
9E6	9EF	Bengali Chakma Syloti_Nagri
9F0	9FB	Bengali
A01	A03	Gurmukhi
A05	A0A	Gurmukhi
A0F	A10	Gurmukhi
A13	A28	Gurmukhi
A2A	A30	Gurmukhi
A32	A33	Gurmukhi
A35	A36	Gurmukhi
A38	A39	Gurmukhi
A3C		Gurmukhi
A3E	A42	Gurmukhi
A47	A48	Gurmukhi
A4B	A4D	Gurmukhi
A51		Gurmukhi
A59	A5C	Gurmukhi
A5E		Gurmukhi
A66	A75	Gurmukhi
A81	A83	Gujarati
A85	A8D	Gujarati
A8F	A91	Gujarati
A93	AA8	Gujarati
AAA	AB0	Gujarati
AB2	AB3	Gujarati
AB5	AB9	Gujarati
ABC	AC5	Gujarati
AC7	AC9	Gujarati
ACB	ACD	Gujarati
AD0		Gujarati
AE0	AE3	Gujarati
AE6	AEF	Gujarati Khojki
AF0	AF1	Gujarati
B01	B03	Oriya
B05	B0C	Oriya
B0F	B10	Oriya
B13	B28	Oriya
B2A	B30	Oriya
B32	B33	Oriya
B35	B39	Oriya
B3C	B44	Oriya
B47	B48	Oriya
B4B	B4D	Oriya
B56	B57	Oriya
B5C	B5D	Oriya
B5F	B63	Oriya
B66	B77	Oriya
B82	B83	Tamil
B85	B8A	Tamil
B8E	B90	Tamil
B92	B95	Tamil
B99	B9A	Tamil
B9C		Tamil
B9E	B9F	Tamil
BA3	BA4	Tamil
BA8	BAA	Tamil
BAE	BB9	Tamil
BBE	BC2	Tamil
BC6	BC8	Tamil
BCA	BCD	Tamil
BD0		Tamil
BD7		Tamil
BE6	BFA	Tamil
C00	C03	Telugu
C05	C0C	Telugu
C0E	C10	Telugu
C12	C28	Telugu
C2A	C39	Telugu
C3D	C44	Telugu
C46	C48	Telugu
C4A	C4D	Telugu
C55	C56	Telugu
C58	C59	Telugu
C60	C63	Telugu
C66	C6F	Telugu
C78	C7F	Telugu
C81	C83	Kannada
C85	C8C	Kannada
C8E	C90	Kannada
C92	CA8	Kannada
CAA	CB3	Kannada
CB5	CB9	Kannada
CBC	CC4	Kannada
CC6	CC8	Kannada
CCA	CCD	Kannada
CD5	CD6	Kannada
CDE		Kannada
CE0	CE3	Kannada
CE6	CEF	Kannada
CF1	CF2	Kannada
D01	D03	Malayalam
D05	D0C	Malayalam
D0E	D10	Malayalam
D12	D3A	Malayalam
D3D	D44	Malayalam
D46	D48	Malayalam
D4A	D4E	Malayalam
D57		Malayalam
D60	D63	Malayalam
D66	D75	Malayalam
D79	D7F	Malayalam
D82	D83	Sinhala
D85	D96	Sinhala
D9A	DB1	Sinhala
DB3	DBB	Sinhala
DBD		Sinhala
DC0	DC6	Sinhala
DCA		Sinhala
DCF	DD4	Sinhala
DD6		Sinhala
DD8	DDF	Sinhala
DE6	DEF	Sinhala
DF2	DF4	Sinhala
E01	E3A	Thai
E3F		Common
E40	E5B	Thai
E81	E82	Lao
E84		Lao
E87	E88	Lao
E8A		Lao
E8D		Lao
E94	E97	Lao
E99	E9F	Lao
EA1	EA3	Lao
EA5		Lao
EA7		Lao
EAA	EAB	Lao
EAD	EB9	Lao
EBB	EBD	Lao
EC0	EC4	Lao
EC6		Lao
EC8	ECD	Lao
ED0	ED9	Lao
EDC	EDF	Lao
F00	F47	Tibetan
F49	F6C	Tibetan
F71	F97	Tibetan
F99	FBC	Tibetan
FBE	FCC	Tibetan
FCE	FD4	Tibetan
FD5	FD8	Common
FD9	FDA	Tibetan
1000	103F	Myanmar
1040	1049	Chakma Myanmar Tai_Le
104A	109F	Myanmar
10A0	10C5	Georgian
10C7		Georgian
10CD		Georgian
10D0	10FA	Georgian
10FB		Common
10FC	10FF	Georgian
1100	11FF	Hangul
1200	1248	Ethiopic
124A	124D	Ethiopic
1250	1256	Ethiopic
1258		Ethiopic
125A	125D	Ethiopic
1260	1288	Ethiopic
128A	128D	Ethiopic
1290	12B0	Ethiopic
12B2	12B5	Ethiopic
12B8	12BE	Ethiopic
12C0		Ethiopic
12C2	12C5	Ethiopic
12C8	12D6	Ethiopic
12D8	1310	Ethiopic
1312	1315	Ethiopic
1318	135A	Ethiopic
135D	137C	Ethiopic
1380	1399	Ethiopic
13A0	13F4	Cherokee
1400	167F	Canadian_Aboriginal
1680	169C	Ogham
16A0	16EA	Runic
16EB	16ED	Common
16EE	16F8	Runic
1700	170C	Tagalog
170E	1714	Tagalog
1720	1734	Hanunoo
1735	1736	Buhid Hanunoo Tagbanwa Tagalog
1740	1753	Buhid
1760	176C	Tagbanwa
176E	1770	Tagbanwa
1772	1773	Tagbanwa
1780	17DD	Khmer
17E0	17E9	Khmer
17F0	17F9	Khmer
1800	1801	Mongolian
1802	1803	Mongolian Phags_Pa
1804		Mongolian
1805		Mongolian Phags_Pa
1806	180E	Mongolian
1810	1819	Mongolian
1820	1877	Mongolian
1880	18AA	Mongolian
18B0	18F5	Canadian_Aboriginal
1900	191E	Limbu
1920	192B	Limbu
1930	193B	Limbu
1940		Limbu
1944	194F	Limbu
1950	196D	Tai_Le
1970	1974	Tai_Le
1980	19AB	New_Tai_Lue
19B0	19C9	New_Tai_Lue
19D0	19DA	New_Tai_Lue
19DE	19DF	New_Tai_Lue
19E0	19FF	Khmer
1A00	1A1B	Buginese
1A1E	1A1F	Buginese
1A20	1A5E	Tai_Tham
1A60	1A7C	Tai_Tham
1A7F	1A89	Tai_Tham
1A90	1A99	Tai_Tham
1AA0	1AAD	Tai_Tham
1AB0	1ABE	Inherited
1B00	1B4B	Balinese
1B50	1B7C	Balinese
1B80	1BBF	Sundanese
1BC0	1BF3	Batak
1BFC	1BFF	Batak
1C00	1C37	Lepcha
1C3B	1C49	Lepcha
1C4D	1C4F	Lepcha
1C50	1C7F	Ol_Chiki
1CC0	1CC7	Sundanese
1CD0	1CD2	Devanagari
1CD3		Common
1CD4	1CE8	Devanagari
1CE9	1CEC	Common
1CED		Devanagari
1CEE	1CF1	Common
1CF2	1CF4	Devanagari
1CF5	1CF6	Common
1CF8	1CF9	Devanagari
1D00	1D25	Latin
1D26	1D2A	Greek
1D2B		Cyrillic
1D2C	1D5C	Latin
1D5D	1D61	Greek
1D62	1D65	Latin
1D66	1D6A	Greek
1D6B	1D77	Latin
1D78		Cyrillic
1D79	1DBE	Latin
1DBF	1DC1	Greek
1DC2	1DF5	Inherited
1DFC	1DFF	Inherited
1E00	1EFF	Latin
1F00	1F15	Greek
1F18	1F1D	Greek
1F20	1F45	Greek
1F48	1F4D	Greek
1F50	1F57	Greek
1F59		Greek
1F5B		Greek
1F5D		Greek
1F5F	1F7D	Greek
1F80	1FB4	Greek
1FB6	1FC4	Greek
1FC6	1FD3	Greek
1FD6	1FDB	Greek
1FDD	1FEF	Greek
1FF2	1FF4	Greek
1FF6	1FFE	Greek
2000	200B	Common
200C	200D	Inherited
200E	2064	Common
2066	2070	Common
2071		Latin
2074	207E	Common
207F		Latin
2080	208E	Common
2090	209C	Latin
20A0	20BD	Common
20D0	20F0	Inherited
2100	2125	Common
2126		Greek
2127	2129	Common
212A	212B	Latin
212C	2131	Common
2132		Latin
2133	214D	Common
214E		Latin
214F	215F	Common
2160	2188	Latin
2189		Common
2190	23FA	Common
2400	2426	Common
2440	244A	Common
2460	27FF	Common
2800	28FF	Braille
2900	2B73	Common
2B76	2B95	Common
2B98	2BB9	Common
2BBD	2BC8	Common
2BCA	2BD1	Common
2C00	2C2E	Glagolitic
2C30	2C5E	Glagolitic
2C60	2C7F	Latin
2C80	2CF3	Coptic
2CF9	2CFF	Coptic
2D00	2D25	Georgian
2D27		Georgian
2D2D		Georgian
2D30	2D67	Tifinagh
2D6F	2D70	Tifinagh
2D7F		Tifinagh
2D80	2D96	Ethiopic
2DA0	2DA6	Ethiopic
2DA8	2DAE	Ethiopic
2DB0	2DB6	Ethiopic
2DB8	2DBE	Ethiopic
2DC0	2DC6	Ethiopic
2DC8	2DCE	Ethiopic
2DD0	2DD6	Ethiopic
2DD8	2DDE	Ethiopic
2DE0	2DFF	Cyrillic
2E00	2E42	Common
2E80	2E99	Han
2E9B	2EF3	Han
2F00	2FD5	Han
2FF0	2FFB	Common
3000		Common
3001	3002	Bopomofo Hangul Han Hiragana Katakana Yi
3003		Bopomofo Hangul Han Hiragana Katakana
3004		Common
3005		Han
3006		Han Hiragana Katakana
3007		Han
3008	3011	Bopomofo Hangul Han Hiragana Katakana Yi
3012		Common
3013		Bopomofo Hangul Han Hiragana Katakana
3014	301B	Bopomofo Hangul Han Hiragana Katakana Yi
301C	301F	Bopomofo Hangul Han Hiragana Katakana
3020		Common
3021	3029	Han
302A	302D	Bopomofo Han
302E	302F	Hangul
3030		Bopomofo Hangul Han Hiragana Katakana
3031	3035	Hiragana Katakana
3036		Common
3037		Bopomofo Hangul Han Hiragana Katakana
3038	303B	Han
303C	303D	Han Hiragana Katakana
303E	303F	Bopomofo Hangul Han Hiragana Katakana
3041	3096	Hiragana
3099	309C	Hiragana Katakana
309D	309F	Hiragana
30A0		Hiragana Katakana
30A1	30FA	Katakana
30FB		Bopomofo Hangul Han Hiragana Katakana Yi
30FC		Hiragana Katakana
30FD	30FF	Katakana
3105	312D	Bopomofo
3131	318E	Hangul
3190	319F	Han Hiragana Katakana
31A0	31BA	Bopomofo
31C0	31E3	Bopomofo Hangul Han Hiragana Katakana
31F0	31FF	Katakana
3200	321E	Hangul
3220	3243	Bopomofo Hangul Han Hiragana Katakana
3244	325F	Common
3260	327E	Hangul
327F		Common
3280	32B0	Bopomofo Hangul Han Hiragana Katakana
32B1	32BF	Common
32C0	32CB	Bopomofo Hangul Han Hiragana Katakana
32CC	32CF	Common
32D0	32FE	Katakana
3300	3357	Katakana
3358	3370	Bopomofo Hangul Han Hiragana Katakana
3371	337A	Common
337B	337F	Bopomofo Hangul Han Hiragana Katakana
3380	33DF	Common
33E0	33FE	Bopomofo Hangul Han Hiragana Katakana
33FF		Common
3400	4DB5	Han
4DC0	4DFF	Common
4E00	9FCC	Han
A000	A48C	Yi
A490	A4C6	Yi
A4D0	A4FF	Lisu
A500	A62B	Vai
A640	A69D	Cyrillic
A69F		Cyrillic
A6A0	A6F7	Bamum
A700	A721	Common
A722	A787	Latin
A788	A78A	Common
A78B	A78E	Latin
A790	A7AD	Latin
A7B0	A7B1	Latin
A7F7	A7FF	Latin
A800	A82B	Syloti_Nagri
A830	A839	Devanagari Gujarati Gurmukhi Kaithi Mahajani Modi Khudawadi Takri Tirhuta
A840	A877	Phags_Pa
A880	A8C4	Saurashtra
A8CE	A8D9	Saurashtra
A8E0	A8FB	Devanagari
A900	A92D	Kayah_Li
A92E		Kayah_Li Latin Myanmar
A92F		Kayah_Li
A930	A953	Rejang
A95F		Rejang
A960	A97C	Hangul
A980	A9CD	Javanese
A9CF		Buginese Javanese
A9D0	A9D9	Javanese
A9DE	A9DF	Javanese
A9E0	A9FE	Myanmar
AA00	AA36	Cham
AA40	AA4D	Cham
AA50	AA59	Cham
AA5C	AA5F	Cham
AA60	AA7F	Myanmar
AA80	AAC2	Tai_Viet
AADB	AADF	Tai_Viet
AAE0	AAF6	Meetei_Mayek
AB01	AB06	Ethiopic
AB09	AB0E	Ethiopic
AB11	AB16	Ethiopic
AB20	AB26	Ethiopic
AB28	AB2E	Ethiopic
AB30	AB5A	Latin
AB5B		Common
AB5C	AB5F	Latin
AB64		Latin
AB65		Greek
ABC0	ABED	Meetei_Mayek
ABF0	ABF9	Meetei_Mayek
AC00	D7A3	Hangul
D7B0	D7C6	Hangul
D7CB	D7FB	Hangul
F900	FA6D	Han
FA70	FAD9	Han
FB00	FB06	Latin
FB13	FB17	Armenian
FB1D	FB36	Hebrew
FB38	FB3C	Hebrew
FB3E		Hebrew
FB40	FB41	Hebrew
FB43	FB44	Hebrew
FB46	FB4F	Hebrew
FB50	FBC1	Arabic
FBD3	FD3D	Arabic
FD3E	FD3F	Common
FD50	FD8F	Arabic
FD92	FDC7	Arabic
FDF0	FDF1	Arabic
FDF2		Arabic Thaana
FDF3	FDFC	Arabic
FDFD		Arabic Thaana
FE00	FE0F	Inherited
FE10	FE19	Common
FE20	FE2D	Inherited
FE30	FE44	Common
FE45	FE46	Bopomofo Hangul Han Hiragana Katakana
FE47	FE52	Common
FE54	FE66	Common
FE68	FE6B	Common
FE70	FE74	Arabic
FE76	FEFC	Arabic
FEFF		Common
FF01	FF20	Common
FF21	FF3A	Latin
FF3B	FF40	Common
FF41	FF5A	Latin
FF5B	FF60	Common
FF61	FF65	Bopomofo Hangul Han Hiragana Katakana Yi
FF66	FF6F	Katakana
FF70		Hiragana Katakana
FF71	FF9D	Katakana
FF9E	FF9F	Hiragana Katakana
FFA0	FFBE	Hangul
FFC2	FFC7	Hangul
FFCA	FFCF	Hangul
FFD2	FFD7	Hangul
FFDA	FFDC	Hangul
FFE0	FFE6	Common
FFE8	FFEE	Common
FFF9	FFFD	Common
10000	1000B	Linear_B
1000D	10026	Linear_B
10028	1003A	Linear_B
1003C	1003D	Linear_B
1003F	1004D	Linear_B
10050	1005D	Linear_B
10080	100FA	Linear_B
10100	10102	Cypriot Linear_B
10107	10133	Cypriot Linear_B
10137	1013F	Cypriot Linear_B
10140	1018C	Greek
10190	1019B	Common
101A0		Greek
101D0	101FC	Common
101FD		Inherited
10280	1029C	Lycian
102A0	102D0	Carian
102E0	102FB	Arabic Coptic
10300	10323	Old_Italic
10330	1034A	Gothic
10350	1037A	Old_Permic
10380	1039D	Ugaritic
1039F		Ugaritic
103A0	103C3	Old_Persian
103C8	103D5	Old_Persian
10400	1044F	Deseret
10450	1047F	Shavian
10480	1049D	Osmanya
104A0	104A9	Osmanya
10500	10527	Elbasan
10530	10563	Caucasian_Albanian
1056F		Caucasian_Albanian
10600	10736	Linear_A
10740	10755	Linear_A
10760	10767	Linear_A
10800	10805	Cypriot
10808		Cypriot
1080A	10835	Cypriot
10837	10838	Cypriot
1083C		Cypriot
1083F		Cypriot
10840	10855	Imperial_Aramaic
10857	1085F	Imperial_Aramaic
10860	1087F	Palmyrene
10880	1089E	Nabataean
108A7	108AF	Nabataean
10900	1091B	Phoenician
1091F		Phoenician
10920	10939	Lydian
1093F		Lydian
10980	1099F	Meroitic_Hieroglyphs
109A0	109B7	Meroitic_Cursive
109BE	109BF	Meroitic_Cursive
10A00	10A03	Kharoshthi
10A05	10A06	Kharoshthi
10A0C	10A13	Kharoshthi
10A15	10A17	Kharoshthi
10A19	10A33	Kharoshthi
10A38	10A3A	Kharoshthi
10A3F	10A47	Kharoshthi
10A50	10A58	Kharoshthi
10A60	10A7F	Old_South_Arabian
10A80	10A9F	Old_North_Arabian
10AC0	10AE6	Manichaean
10AEB	10AF6	Manichaean
10B00	10B35	Avestan
10B39	10B3F	Avestan
10B40	10B55	Inscriptional_Parthian
10B58	10B5F	Inscriptional_Parthian
10B60	10B72	Inscriptional_Pahlavi
10B78	10B7F	Inscriptional_Pahlavi
10B80	10B91	Psalter_Pahlavi
10B99	10B9C	Psalter_Pahlavi
10BA9	10BAF	Psalter_Pahlavi
10C00	10C48	Old_Turkic
10E60	10E7E	Arabic
11000	1104D	Brahmi
11052	1106F	Brahmi
1107F		Brahmi
11080	110C1	Kaithi
110D0	110E8	Sora_Sompeng
110F0	110F9	Sora_Sompeng
11100	11134	Chakma
11136	11143	Chakma
11150	11176	Mahajani
11180	111C8	Sharada
111CD		Sharada
111D0	111DA	Sharada
111E1	111F4	Sinhala
11200	11211	Khojki
11213	1123D	Khojki
112B0	112EA	Khudawadi
112F0	112F9	Khudawadi
11301	11303	Grantha
11305	1130C	Grantha
1130F	11310	Grantha
11313	11328	Grantha
1132A	11330	Grantha
11332	11333	Grantha
11335	11339	Grantha
1133C	11344	Grantha
11347	11348	Grantha
1134B	1134D	Grantha
11357		Grantha
1135D	11363	Grantha
11366	1136C	Grantha
11370	11374	Grantha
11480	114C7	Tirhuta
114D0	114D9	Tirhuta
11580	115B5	Siddham
115B8	115C9	Siddham
11600	11644	Modi
11650	11659	Modi
11680	116B7	Takri
116C0	116C9	Takri
118A0	118F2	Warang_Citi
118FF		Warang_Citi
11AC0	11AF8	Pau_Cin_Hau
12000	12398	Cuneiform
12400	1246E	Cuneiform
12470	12474	Cuneiform
13000	1342E	Egyptian_Hieroglyphs
16800	16A38	Bamum
16A40	16A5E	Mro
16A60	16A69	Mro
16A6E	16A6F	Mro
16AD0	16AED	Bassa_Vah
16AF0	16AF5	Bassa_Vah
16B00	16B45	Pahawh_Hmong
16B50	16B59	Pahawh_Hmong
16B5B	16B61	Pahawh_Hmong
16B63	16B77	Pahawh_Hmong
16B7D	16B8F	Pahawh_Hmong
16F00	16F44	Miao
16F50	16F7E	Miao
16F8F	16F9F	Miao
1B000		Katakana
1B001		Hiragana
1BC00	1BC6A	Duployan
1BC70	1BC7C	Duployan
1BC80	1BC88	Duployan
1BC90	1BC99	Duployan
1BC9C	1BCA3	Duployan
1D000	1D0F5	Common
1D100	1D126	Common
1D129	1D166	Common
1D167	1D169	Inherited
1D16A	1D17A	Common
1D17B	1D182	Inherited
1D183	1D184	Common
1D185	1D18B	Inherited
1D18C	1D1A9	Common
1D1AA	1D1AD	Inherited
1D1AE	1D1DD	Common
1D200	1D245	Greek
1D300	1D356	Common
1D360	1D371	Common
1D400	1D454	Common
1D456	1D49C	Common
1D49E	1D49F	Common
1D4A2		Common
1D4A5	1D4A6	Common
1D4A9	1D4AC	Common
1D4AE	1D4B9	Common
1D4BB		Common
1D4BD	1D4C3	Common
1D4C5	1D505	Common
1D507	1D50A	Common
1D50D	1D514	Common
1D516	1D51C	Common
1D51E	1D539	Common
1D53B	1D53E	Common
1D540	1D544	Common
1D546		Common
1D54A	1D550	Common
1D552	1D6A5	Common
1D6A8	1D7CB	Common
1D7CE	1D7FF	Common
1E800	1E8C4	Mende_Kikakui
1E8C7	1E8D6	Mende_Kikakui
1EE00	1EE03	Arabic
1EE05	1EE1F	Arabic
1EE21	1EE22	Arabic
1EE24		Arabic
1EE27		Arabic
1EE29	1EE32	Arabic
1EE34	1EE37	Arabic
1EE39		Arabic
1EE3B		Arabic
1EE42		Arabic
1EE47		Arabic
1EE49		Arabic
1EE4B		Arabic
1EE4D	1EE4F	Arabic
1EE51	1EE52	Arabic
1EE54		Arabic
1EE57		Arabic
1EE59		Arabic
1EE5B		Arabic
1EE5D		Arabic
1EE5F		Arabic
1EE61	1EE62	Arabic
1EE64		Arabic
1EE67	1EE6A	Arabic
1EE6C	1EE72	Arabic
1EE74	1EE77	Arabic
1EE79	1EE7C	Arabic
1EE7E		Arabic
1EE80	1EE89	Arabic
1EE8B	1EE9B	Arabic
1EEA1	1EEA3	Arabic
1EEA5	1EEA9	Arabic
1EEAB	1EEBB	Arabic
1EEF0	1EEF1	Arabic
1F000	1F02B	Common
1F030	1F093	Common
1F0A0	1F0AE	Common
1F0B1	1F0BF	Common
1F0C1	1F0CF	Common
1F0D1	1F0F5	Common
1F100	1F10C	Common
1F110	1F12E	Common
1F130	1F16B	Common
1F170	1F19A	Common
1F1E6	1F1FF	Common
1F200		Hiragana
1F201	1F202	Common
1F210	1F23A	Common
1F240	1F248	Common
1F250	1F251	Common
1F300	1F32C	Common
1F330	1F37D	Common
1F380	1F3CE	Common
1F3D4	1F3F7	Common
1F400	1F4FE	Common
1F500	1F54A	Common
1F550	1F579	Common
1F57B	1F5A3	Common
1F5A5	1F642	Common
1F645	1F6CF	Common
1F6E0	1F6EC	Common
1F6F0	1F6F3	Common
1F700	1F773	Common
1F780	1F7D4	Common
1F800	1F80B	Common
1F810	1F847	Common
1F850	1F859	Common
1F860	1F887	Common
1F890	1F8AD	Common
20000	2A6D6	Han
2A700	2B734	Han
2B740	2B81D	Han
2F800	2FA1D	Han
E0001		Common
E0020	E007F	Common
E0100	E01EF	Inherited
END
