# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 7.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.  Use Unicode::UCD to access the Unicode character data
# base.


return <<'END';
V66
4352
4448
9001
9003
11904
11930
11931
12020
12032
12246
12272
12284
12289
12351
12353
12439
12441
12544
12549
12590
12593
12687
12688
12731
12736
12772
12784
12831
12832
12872
12880
13055
13056
19904
19968
42125
42128
42183
43360
43389
44032
55204
63744
64256
65040
65050
65072
65107
65108
65127
65128
65132
110592
110594
127488
127491
127504
127547
127552
127561
127568
127570
131072
196606
196608
262142
END
