# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 7.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.  Use Unicode::UCD to access the Unicode character data
# base.


return <<'END';
V40
746
748
12289
12292
12296
12306
12307
12320
12330
12334
12336
12337
12343
12344
12350
12352
12539
12540
12549
12590
12704
12731
12736
12772
12832
12868
12928
12977
12992
13004
13144
13169
13179
13184
13280
13311
65093
65095
65377
65382
END
