# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 7.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.  Use Unicode::UCD to access the Unicode character data
# base.


return <<'END';
V56
11904
11930
11931
12020
12032
12246
12289
12292
12293
12306
12307
12320
12321
12334
12336
12337
12343
12352
12539
12540
12688
12704
12736
12772
12832
12868
12928
12977
12992
13004
13144
13169
13179
13184
13280
13311
13312
19894
19968
40909
63744
64110
64112
64218
65093
65095
65377
65382
131072
173783
173824
177973
177984
178206
194560
195102
END
