# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 7.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.  Use Unicode::UCD to access the Unicode character data
# base.


return <<'END';
V44
12289
12292
12294
12295
12296
12306
12307
12320
12336
12342
12343
12344
12348
12352
12441
12445
12448
12544
12688
12704
12736
12772
12784
12800
12832
12868
12928
12977
12992
13004
13008
13055
13056
13169
13179
13184
13280
13311
65093
65095
65377
65440
110592
110593
END
