# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 7.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.  Use Unicode::UCD to access the Unicode character data
# base.


return <<'END';
V100
48
58
1632
1642
1776
1786
1984
1994
2406
2416
2534
2544
2662
2672
2790
2800
2918
2928
3046
3056
3174
3184
3302
3312
3430
3440
3558
3568
3664
3674
3792
3802
3872
3882
4160
4170
4240
4250
6112
6122
6160
6170
6470
6480
6608
6618
6784
6794
6800
6810
6992
7002
7088
7098
7232
7242
7248
7258
42528
42538
43216
43226
43264
43274
43472
43482
43504
43514
43600
43610
44016
44026
65296
65306
66720
66730
69734
69744
69872
69882
69942
69952
70096
70106
70384
70394
70864
70874
71248
71258
71360
71370
71904
71914
92768
92778
93008
93018
120782
120832
END
