# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 7.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.  Use Unicode::UCD to access the Unicode character data
# base.


return <<'END';
V62
105
107
303
304
585
586
616
617
669
670
690
691
1011
1012
1110
1111
1112
1113
7522
7523
7574
7575
7588
7589
7592
7593
7725
7726
7883
7884
8305
8306
8520
8522
11388
11389
119842
119844
119894
119896
119946
119948
119998
120000
120050
120052
120102
120104
120154
120156
120206
120208
120258
120260
120310
120312
120362
120364
120414
120416
120466
120468
END
