# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 7.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.  Use Unicode::UCD to access the Unicode character data
# base.


return <<'END';
V81
2144
2208
7296
7360
12256
12272
43888
43968
66048
66176
66528
66560
66736
66816
66928
67072
67456
67584
67760
67840
67904
67968
68256
68288
68528
68608
68688
69216
69248
69632
70224
70320
70528
70784
70880
71040
71264
71296
71376
71840
71936
72384
72448
73728
74880
77824
78896
92160
92784
92880
93072
93952
94112
110592
110848
113664
113840
118784
119376
119552
119680
119808
120832
124928
125152
126464
126720
126976
129280
131072
173792
173824
178208
194560
195104
917504
917632
917760
918000
983040
1114112
END
