# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 7.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.  Use Unicode::UCD to access the Unicode character data
# base.


return <<'END';
V70
578
592
891
894
1231
1232
1274
1280
1296
1300
1466
1467
1984
2043
2427
2429
2430
2432
3298
3300
3313
3315
6912
6988
6992
7037
7620
7627
7678
7680
8428
8432
8525
8527
8580
8581
9180
9192
9906
9907
10183
10187
11028
11035
11040
11044
11360
11373
11380
11384
42775
42779
42784
42786
43072
43128
67840
67866
67871
67872
73728
74607
74752
74851
74864
74868
119648
119666
120778
120780
END
