# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 7.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.  Use Unicode::UCD to access the Unicode character data
# base.


return <<'END';
V64
0
9
14
28
127
133
134
160
173
174
6158
6159
8203
8206
8288
8294
8298
8304
64976
65008
65279
65280
65520
65529
65534
65536
113824
113828
119155
119163
131070
131072
196606
196608
262142
262144
327678
327680
393214
393216
458750
458752
524286
524288
589822
589824
655358
655360
720894
720896
786430
786432
851966
851968
917502
917760
918000
921600
983038
983040
1048574
1048576
1114110
1114112
END
