# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 7.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.  Use Unicode::UCD to access the Unicode character data
# base.


return <<'END';
V76
3585
3643
3648
3663
3713
3715
3716
3717
3719
3721
3722
3723
3725
3726
3732
3736
3737
3744
3745
3748
3749
3750
3751
3752
3754
3756
3757
3770
3771
3774
3776
3781
3782
3783
3784
3790
3804
3808
4096
4160
4176
4240
4250
4256
6016
6100
6103
6104
6108
6110
6480
6510
6512
6517
6528
6572
6576
6602
6618
6619
6622
6624
6688
6751
6752
6781
6816
6830
43488
43504
43514
43519
43616
43715
43739
43744
END
