# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 7.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.  Use Unicode::UCD to access the Unicode character data
# base.


return <<'END';
V80
2381
2382
2509
2510
2637
2638
2765
2766
2893
2894
3021
3022
3149
3150
3277
3278
3405
3406
3530
3531
3642
3643
3972
3973
4153
4155
5908
5909
5940
5941
6098
6099
6752
6753
6980
6981
7082
7084
7154
7156
11647
11648
43014
43015
43204
43205
43347
43348
43456
43457
43766
43767
44013
44014
68159
68160
69702
69703
69759
69760
69817
69818
69939
69941
70080
70081
70197
70198
70378
70379
70477
70478
70850
70851
71103
71104
71231
71232
71350
71351
END
