# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 7.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.  Use Unicode::UCD to access the Unicode character data
# base.


return <<'END';
V78
0
48
58
65
91
95
96
97
123
168
169
170
171
175
176
178
182
183
187
188
191
192
215
216
247
248
847
848
1564
1565
4447
4449
5760
5761
6068
6070
6155
6159
8192
8255
8257
8276
8277
8304
8592
9312
9472
10102
10132
11264
11776
11904
12288
12292
12296
12321
12336
12337
12644
12645
64830
64832
65024
65040
65093
65095
65279
65280
65440
65441
65520
65529
113824
113828
119155
119163
917504
921600
END
