# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 7.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.  Use Unicode::UCD to access the Unicode character data
# base.


return <<'END';
V66
2392
2400
2524
2526
2527
2528
2611
2612
2614
2615
2649
2652
2654
2655
2908
2910
3907
3908
3917
3918
3922
3923
3927
3928
3932
3933
3945
3946
3958
3959
3960
3961
3987
3988
3997
3998
4002
4003
4007
4008
4012
4013
4025
4026
10972
10973
64285
64286
64287
64288
64298
64311
64312
64317
64318
64319
64320
64322
64323
64325
64326
64335
119134
119141
119227
119233
END
